### PR TITLE
Assignment 2 part 1 no bonus

### PR DESCRIPTION
**Pull request by Sky322**
may do some bonus before class or may wait until part 2

### CODE REVIEW

**Review by SamBumgardner — CHANGES_REQUESTED** [review]
Your work looks good so far, but you currently have your `export` and `.vscode` folders getting pushed up to your project along with your code changes.

`export` should be excluded because the files in there can be large, they change after pretty much every build, and they're easily built after cloning the repository with something like lime test neko. There's not really a benefit to keeping them in your project, and it does make the project's history hard to read.

A similar idea applies to the `.vscode` directory. People that clone your repository won't necessarily use vscode at all, and even if they do they may prefer different configuration. It's best to keep the repository as minimal as possible in this case, and leave each contributor to set up their own preferred ide config.

It looks like you have a correct `.gitignore` file in the branch now, so all you should need to do is delete the `export` and `.vscode`. After you commit their deletion, you're free to recreate them without accidentally pushing them into your git repository.

**Review by SamBumgardner — COMMENTED** [review]
Okay, everything for part 1 looks good to me! Thanks for finishing the cleanup.

Don't forget that part 2 is due on Wednesday.

**Comment by Sky322** [comment]
finished the rest not sure if I was supposed to merge last pull request before doing this and create another or not but all my commits are here. Also i did the keyboard input bonus so I did not add multiple hero objects or randomize their directions.

**Review by SamBumgardner — APPROVED** [review]
Looks good, feel free to merge when you're ready.

**Pull request merged**
